kudinov-fedor/python_at_2021

tests/mizo/constants.py, tests/mizo/generate_user_names_and_set_test_password.py, tests/mizo/perf_test.py
=> LocustClient

tests/mizo/apiClient_for_locust.py, tests/mizo/constants.py, tests/mizo/inheritance_from_api_client.py
=> inheritance from api client

tests/khrystynatk/hw1_khr_check_password.py, tests/khrystynatk/test_hw1_khr_check_password.py
=> hw1_check_pass

tests/khrystynatk/hw1_khr_Use_config.py, tests/khrystynatk/test_hw1_khr_Use_config.py
=> hw1_use_config

tests/khrystynatk/hw1_khr_Not_reliable_function.py, tests/khrystynatk/test_hw1_khr_Not_reliable_function.py
=> hw1_Not_reliable_function

tests/itymc/test_password.py
=> itymc first commit

tests/ysemenov/test_check_password.py
Homework1: test check_password
=> hw1: test check_password

tests/khrystynatk/hw1_khr_Not_reliable_function_2.py, tests/khrystynatk/hw1_khr_Not_reliable_function_3.py, tests/khrystynatk/test_hw1_khr_Not_reliable_function_2.py, tests/khrystynatk/test_hw1_khr_Not_reliable_function_3.py
=> hw1_Not_reliable_function_2_and_3

tests/khrystynatk/test_hw2_khr_Selenium_WebDriver.py
@kudinov-fedor review please. If the overall approach is ok, I'll cover with more tests.
=> Selenium WebDriver 1.0

tests/threc/HW_saucedemo/conftest.py, tests/threc/HW_saucedemo/test_site_order.py
=> Tests for HW2

tests/threc/HW_saucedemo/conftest.py, tests/threc/HW_saucedemo/costants.py, tests/threc/HW_saucedemo/locators.py, tests/threc/HW_saucedemo/test_site_order.py
Change locators to xpath or css
=> tests for saucedemo site with changed locators

tests/khrystynatk/locators.py, tests/khrystynatk/test_hw3_khr_Locators.py
=> khr_hw3_Locators

tests/threc/HW4_demoqa/conftest.py, tests/threc/HW4_demoqa/constants.py, tests/threc/HW4_demoqa/test_textbox.py
=> tests for demoqa/text-box

tests/ysemenov/hw2/test_sauce_orders.py
- added HW2 tests for www.saucedemo.com
=> Homework 2

tests/mariana_petrushanska/test_selenium_hw3/conftest.py, tests/mariana_petrushanska/test_selenium_hw3/constants.py, tests/mariana_petrushanska/test_selenium_hw3/locators.py, tests/mariana_petrushanska/test_selenium_hw3/test_buttons.py, tests/mariana_petrushanska/test_selenium_hw3/test_dynamic_properties.py, tests/mariana_petrushanska/test_selenium_hw_2/conftest.py, tests/mariana_petrushanska/test_selenium_hw_2/constants.py, tests/mariana_petrushanska/test_selenium_hw_2/locators.py, tests/mariana_petrushanska/test_selenium_hw_2/test_selenium_updated_locators.py
Test for:
1. Buttons (double click, right click, regular click).
2. Dynamic properties (wait till button is enabled, color change, visible after some time).
=> HW 4. Test demoqa.

tests/ysemenov/hw2/test_sauce_orders.py, tests/ysemenov/hw3/locators.py
- added hw3/locators.py with locators
- replaced id/css/xpath with css/xpath/css respectively
- updated test with references to locators
=> homework 3 (locators)

tests/sradu/homework_2/test_saucedemo.py, tests/sradu/homework_2/utils.py
**Description:**
- reorganised initial code 
- added 2 tests `test_menu_items` , `test_prices_in_ascending_order`
**Screenshots:**
=> SR-2: homework 2

tests/sradu/homework_3/constants.py, tests/sradu/homework_3/locators.py, tests/sradu/homework_3/test_saucedemo.py, tests/sradu/homework_3/utils.py
***Description***
- changed locators to alternative option
- optimised `test_saucedemo.py` to read locators from separate file 
***Screenshot***
=> SR-3: added homework 3

tests/sradu/homework_3/test_saucedemo.py, tests/sradu/homework_4/conftest.py, tests/sradu/homework_4/constants.py, tests/sradu/homework_4/locators.py, tests/sradu/homework_4/test_demoqa.py, tests/sradu/homework_4/utils.py
***Description***
- removed unused import from homework_3
- added homework_4 with the following structure:
- conftest -> fixture 
- constants -> repetitive values
- locators -> used xpath as a standard
- test_demoqa -> 2 test scenarious: `test_alert_confirm_box_ok`, `test_droppable`
- utils -> functions utilized by test_demoqa
***Screenshots***
=> SR-4: homework 4

tests/ysemenov/hw7/api_client.py, tests/ysemenov/hw7/constants.py, tests/ysemenov/hw7/test_book_store_api.py
- added api client and some api tests
=> homework 7: add rest api tests for demoqa
